<?php
/**
 * This file is part of the RedKite CMS Application and it is distributed
 * under the GPL LICENSE Version 2.0. To use this application you must leave
 * intact this copyright notice.
 *
 * Copyright (c) RedKite Labs <info@redkite-labs.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 *
 * For extra documentation and help please visit http://www.redkite-labs.com
 *
 * @license    GPL LICENSE Version 2.0
 *
 */

namespace RedKiteCms\EventSystem\Listener\Request;


use JMS\Serializer\Serializer;
use RedKiteCms\Configuration\ConfigurationHandler;
use RedKiteCms\Content\Block\BlockFactory;
use RedKiteCms\Content\BlockManager\BlockManagerEdit;
use RedKiteCms\Content\PageCollection\PagesCollectionParser;
use RedKiteCms\Content\Theme\ThemeSlotsGenerator;
use RedKiteCms\Content\Theme\ThemeAligner;
use RedKiteCms\Content\Theme\ThemeGenerator;
use RedKiteCms\FilesystemEntity\Page;
use RedKiteCms\Tools\FilesystemTools;
use Symfony\Component\Finder\Finder;
use Symfony\Component\HttpKernel\Event\GetResponseEvent;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Security\Core\SecurityContext;

/**
 * Class ThemeAlignerListener listens to Kernel Request to align the RedKite CMS autogenerated files that defines the theme in use in the current site, according to changes made with the theme design
 *
 * @author  RedKite Labs <webmaster@redkite-labs.com>
 * @package RedKiteCms\EventSystem\Listener\Request
 */
class QueueListener
{
    /**
     * @type \RedKiteCms\Configuration\ConfigurationHandler
     */
    private $configurationHandler;
    /**
     * @type \RedKiteCms\Content\PageCollection\PagesCollectionParser
     */
    private $pagesCollectionParser;
    /**
     * @type \Symfony\Component\Security\Core\SecurityContext
     */
    private $securityContext;
    /**
     * @var \RedKiteCms\Content\Theme\ThemeGenerator
     */
    private $themeGenerator;
    /**
     * @var \RedKiteCms\Content\Theme\ThemeSlotsGenerator
     */
    private $slotsGenerator;
    /**
     * @var \RedKiteCms\Content\Theme\ThemeAligner
     */
    private $themeAligner;


    public function __construct(ConfigurationHandler $configurationHandler, Serializer $serializer, BlockFactory $blockFactory)
    {
        $this->configurationHandler = $configurationHandler;
        $this->serializer = $serializer;
        $this->blockFactory = $blockFactory;
    }

    /**
     * Aligns the site slots
     *
     * @param GetResponseEvent $event
     */
    public function onKernelRequest(GetResponseEvent $event)
    {
        $finder = new Finder();
        $files = $finder->files()->depth(0)->name('*.json')->in($this->configurationHandler->siteDir() . '/queue');
        foreach($files  as $file) {
            $queue = json_decode(FilesystemTools::readFile($file), true);
            foreach($queue as $operation) {
                $data = $operation["data"];
                if ($operation["action"] == 'edit') {
                    $serializer = $this->serializer;
                    $editOptions = array(
                        'page' => $data['page'],
                        'language' => $data['language'],
                        'country' => $data['country'],
                        'slot' => $data['slot'],
                        'blockname' => $data['name'],
                    );

                    $blockManager = new BlockManagerEdit($serializer, $this->blockFactory, new OptionsResolver());
                    $blockManager->edit(
                        $this->configurationHandler->siteDir(),
                        $editOptions,
                        'admin',
                        $data['data']
                    );
                }
                /*
                if ($operation["action"] == 'remove') {
                    $serializer = $this->serializer;
                    $editOptions = array(
                        'page' => $data['page'],
                        'language' => $data['language'],
                        'country' => $data['country'],
                        'slot' => $data['slot'],
                        'blockname' => $data['name'],
                    );

                    $blockManager = new BlockManagerEdit($serializer, $this->blockFactory, new OptionsResolver());
                    $blockManager->edit(
                        $this->configurationHandler->siteDir(),
                        $editOptions,
                        'admin',
                        $data['data']
                    );
                }*/
            }
        }
        
    }
} 