<?php

namespace AlphaLemon\ThemeEngineBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ThemesController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AlphaLemon\ThemeEngineBundle\Controller\ThemesController();
        return $instance;
    }
}
