<?php

namespace AlphaLemon\ThemeEngineBundle\Core\Rendering\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class BaseFrontendController__JMSInjector
{
    public static function inject($container) {
        $instance = new \AlphaLemon\ThemeEngineBundle\Core\Rendering\Controller\BaseFrontendController();
        return $instance;
    }
}
