<?php

namespace Sensio\Bundle\DistributionBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ConfiguratorController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Sensio\Bundle\DistributionBundle\Controller\ConfiguratorController();
        return $instance;
    }
}
