<?php

namespace Symfony\Bundle\AsseticBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class AsseticController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Symfony\Bundle\AsseticBundle\Controller\AsseticController();
        return $instance;
    }
}
