<?php

namespace Symfony\Bundle\FrameworkBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class InternalController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Symfony\Bundle\FrameworkBundle\Controller\InternalController();
        return $instance;
    }
}
