<?php

namespace Symfony\Bundle\WebProfilerBundle\Controller;

/**
 * This code has been auto-generated by the JMSDiExtraBundle.
 *
 * Manual changes to it will be lost.
 */
class ExceptionController__JMSInjector
{
    public static function inject($container) {
        $instance = new \Symfony\Bundle\WebProfilerBundle\Controller\ExceptionController();
        return $instance;
    }
}
